# Generated by Django 4.0.4 on 2022-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='patient_profile_picture/'),
            preserve_default=False,
        ),
    ]
