# Generated by Django 4.0.5 on 2022-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0002_medicalprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='bmi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
