# Generated by Django 4.0.4 on 2022-09-11 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_auth', '0003_medicalprofile_bmi_medicalprofile_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Uploaded_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_19', models.ImageField(blank=True, null=True, upload_to='patient_covid_19/')),
                ('heart_disease', models.BooleanField(blank=True, default=False, null=True)),
                ('brain_tumor', models.ImageField(blank=True, null=True, upload_to='brain_tumor/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
